export const LOADER = 'LOADER'
export const GIF_LOADER = 'GIF_LOADER'
export const TOTAL_REVENUE_STAT = 'TOTAL_REVENUE_STAT'
export const CHART_DATA_SUM = 'CHART_DATA_SUM'
export const DOMAIN_DATA = 'DOMAIN_DATA'

export const DEFAULT_TRAFFIC = "DEFAULT_TRAFFIC";
export const CHART_TRAFFIC = "CHART_TRAFFIC"